import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Lato } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";


const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});



const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const verah = localFont({
  src: [
    {
      path: "../../public/commercial/fonts/Verah___.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/commercial/fonts/Verahb__.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-verah",
})

const gotham = localFont({
  src: [
    {
      path: "../../public/commercial/fonts/icielgothammediumregular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/commercial/fonts/iCielGothamBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/commercial/fonts/icielgothamultraregular.otf",
      weight: "900",
      style: "normal",
    },

  ],
  variable: "--font-gotham",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${gotham.variable} ${verah.variable}`} suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
